#!/bin/bash

## Description: Performs a default drupal installation
## Usage: install
## Example: "ddev install"

drush site:install standard --account-name=admin --account-pass=admin --site-name="Drupal 10" -y
# drush en admin_toolbar admin_toolbar_tools config_inspector devel
