#!/bin/bash

## Description: Run Nightwatch
## Usage: nightwatch [flags] [args]
## Example: "ddev nightwatch" or "ddev nightwatch --tag core"

# Installs dependencies if not already run.
if [ ! -d /var/www/html/repos/drupal/core/node_modules ]; then
  yarn --cwd /var/www/html/repos/drupal/core install
fi

yarn --cwd /var/www/html/repos/drupal/core test:nightwatch $@
