#!/bin/bash

## Description: Clean up test results
## Usage: tests-cleanup
## Example: "ddev tests-cleanup"

TOP_LEVEL="/var/www/html"
cd $TOP_LEVEL

if [ ! -d "web/sites/simpletest/browser_output" ]
then
  echo "The expected folder web/sites/simpletest/browser_output does not exist."
  exit
fi

rm web/sites/simpletest/browser_output/*.counter
rm web/sites/simpletest/browser_output/*.html

echo "Test files removed."
